version: "3.7"

services:

  sorting:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0:80
    environment:
      C_FORCE_ROOT: "true"
    ports:
      - "8002:80"
    volumes: 
      - ./:/main
