# Generated by Django 4.1 on 2023-03-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_navigation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='index.navigation'),
        ),
    ]
