# Generated by Django 4.1 on 2023-03-31 04:59

from django.db import migrations, models
import django.utils.timezone
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_profile_middle_name_profile_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='docs',
            field=models.FileField(default=django.utils.timezone.now, upload_to=index.models.upload_docs),
            preserve_default=False,
        ),
    ]
